### ISSUE TITLE
uninitialized constant Jquery::Ui::Rails::JQUERY_UI_VERSION

### ISSUE THREAD

**Issue by mltsy** [styx/jquery-ui-rails-cdn#1]
This is the error I get when I try to run my app with this gem installed.  I looked in the jquery-ui-rails gem and I don't see it setting this constant anywhere.  Does this work for you?  Where is the constant supposed to come from?

**Comment by styx** [comment]
Yeah, that the stuff I forgotten to include to the Readme. For now the required patch is not merged into jquery-ui-rails and you need to use this fork for i.e.

``` ruby
gem 'jquery-ui-rails', github: 'techbang/jquery-ui-rails'
```

I'll add some info into readme soon.

**Comment by styx** [comment]
Hey, great news! At last the issue is fixed! See readme file for details.
