### ISSUE TITLE
specify jquery version

### ISSUE THREAD

**Issue by chrishough** [styx/jquery-ui-rails-cdn#2]
any way to specify the version of jquery we want to use? 

https://developers.google.com/speed/libraries/devguide#jquery

**Comment by styx** [comment]
Nope, it is controlled by jQuery-UI library via Jquery::Ui::Rails::JQUERY_UI_VERSION

**Comment by styx** [comment]
Hey, great news! At last the issue is fixed! See readme file for details.

**Comment by chrishough** [comment]
coolio `:)`
