### ISSUE TITLE
Any update on the "uninitialized constant Jquery::Ui::Rails::JQUERY_UI_VERSION" error?

### ISSUE THREAD

**Issue by brightball** [styx/jquery-ui-rails-cdn#3]
I see the note about it in the readme, but it's been almost a year and this is the recommended gem from jquery-rails-cdn.

**Comment by styx** [comment]
Seems, it will never be done. See https://github.com/joliss/jquery-ui-rails/pull/19 for details. There you will find some words why this gem is not OK in terms of compatibility and version will never be merged. I think I should add a note to the top of the README to not bother people more with this.

**Comment by styx** [comment]
I can only recommend you to use a more generic library https://github.com/lukehorvat/cdn_assets

**Comment by styx** [comment]
Hey, great news! At last the issue is fixed! See readme file for details.
