### ISSUE TITLE
Could I include only part of jQueryUI ?

### ISSUE THREAD

**Issue by pruzicka** [styx/jquery-ui-rails-cdn#6]
Hi,
when I use only gem 'jquery-ui-rails' and I specify //= require jquery.ui.effect-highlight
in application.js server indeed serves only that part 
12:33:22 web.1  | 127.0.0.1 - - [18/Dec/2013 12:33:22] "GET /jquery.ui.effect.js?body=1 HTTP/1.1" 304 - 0.0506
12:33:22 web.1  | 127.0.0.1 - - [18/Dec/2013 12:33:22] "GET /jquery.ui.effect-highlight.js?body=1 HTTP/1.1" 304 - 0.0415
However when I add gem 'jquery-ui-rails-cdn' to Gemfile, whole jQueryUI is served. Is that expected behavior ?
Thanks
Petr

**Comment by styx** [comment]
Nope, CDNs provide only full library.

**Comment by pruzicka** [comment]
Thanks ! It's OK with production but in development it's slowing me down if every reload loads all the parts of jQueryUI. Thanks a lot anyway
