### ISSUE TITLE
How do get only datepicker?

### ISSUE THREAD

**Issue by napster3000** [styx/jquery-ui-rails-cdn#9]
I've removed anything from application.js, so there is just this in layouts/application.html.erb

  <%= jquery_ui_include_tag :google %>

If I would to use just datepicker instead of the whole library?

**Comment by styx** [comment]
Most of CDN services provides a full jquery-ui library and doesn't provide individual components. This gem is designed to provide the same experience with different CDNs, so there is no way to load only datepicker from via this gem.
